BREAKING CHANGE - CORE 'Add Azure DevOps Managed Identity Support'
dsccommunity/AzureDevOpsDsc pull request #34
Opened 2024-01-29 04:17 UTC by ZanattaMichael

#### Pull Request (PR) description
Here’s a reworded version of the Pull Request:

The Pull Request introduces Azure DevOps Managed Identity by enabling the module to retrieve an AzureDevops API Token. This eliminates the need for a PAT. The feature is only available within Invoke-DSCResource and can be used within an Azure VM. The module achieves this by querying GET 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/' HTTP/1.1 Metadata: true.

#### This Pull Request (PR) fixes the following issues

#### Task list

- [ ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [X] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2024-02-04 19:12 UTC, kilasuit requested changes

2024-02-04 19:12 UTC, kilasuit commented on tests/Unit/Modules/AzureDevOpsDsc.Common/AzureDevOpsDsc.Common.TestInitialization.ps1
> +Function Split-RecurivePath {
```suggestion
Function Split-RecursivePath {
```

2024-02-04 19:12 UTC, kilasuit commented on tests/Unit/Modules/AzureDevOpsDsc.Common/AzureDevOpsDsc.Common.TestInitialization.ps1
> +Import-Module -Name $script:dscModuleFile #-Force
What was the reason in commenting out the `-Force`

2024-02-04 19:12 UTC, kilasuit commented on tests/Unit/Modules/AzureDevOpsDsc.Common/AzureDevOpsDsc.Common.TestInitialization.ps1
> +Import-Module -Name $script:subModuleFile #-Force #-Verbose
What was the reason in commenting out the `-Force` & `-Verbose`

2024-02-25 01:56 UTC, ZanattaMichael commented on tests/Unit/Modules/AzureDevOpsDsc.Common/AzureDevOpsDsc.Common.TestInitialization.ps1
> +Import-Module -Name $script:subModuleFile #-Force #-Verbose
Testing. I forgot to remove it.

2024-02-25 01:56 UTC, ZanattaMichael commented on tests/Unit/Modules/AzureDevOpsDsc.Common/AzureDevOpsDsc.Common.TestInitialization.ps1
> +Import-Module -Name $script:dscModuleFile #-Force
Testing. I forgot to remove it.

2024-02-25 22:08 UTC, kilasuit requested changes

2024-02-25 22:08 UTC, kilasuit commented on tests/Unit/Modules/AzureDevOpsDsc.Common/AzureDevOpsDsc.Common.TestInitialization.ps1
> +$script:RepositoryRoot = Split-RecurivePath $PSScriptRoot -Times 4
```suggestion
$script:RepositoryRoot = Split-RecursivePath $PSScriptRoot -Times 4
```

2024-02-25 22:08 UTC, kilasuit commented on tests/Unit/Modules/AzureDevOpsDsc.Common/AzureDevOpsDsc.Common.TestInitialization.ps1
> +$script:RepositoryRoot = Split-RecurivePath $PSScriptRoot -Times 4
Sorry I missed this last time too

2024-02-25 22:09 UTC, kilasuit submitted a review, later dismissed

2024-02-25 23:39 UTC, ZanattaMichael commented
@kilasuit So the module minimum version will be version 7. Is that going to be an issue? I figured that it wouldn't since the module resources are incomplete.

2024-04-25 12:22 UTC, kilasuit commented
Sorry on the delay in getting back to you on this, I know it's been a while.

> @kilasuit So the module minimum version will be version 7. Is that going to be an issue? I figured that it wouldn't since the module resources are incomplete and it's easier to write for the new version.

As you'll have seen in the DSC Channel in the PowerShell Discord/slack DSC I've asked others for input on this generally with modules part of the DSCCommunity

Personally I'm ok with it, if we do can potentially have releases that are both v5 and v7 compatible (for those orgs not upgrading to v7 yet) side by side & to do that we'd need to
- Bump the major version of the module with this release to show that v7 language features are being used
- merge this into a v7 branch not the main branch so can leave main as is for now for v5 compatible changes
- update docs about this 

All of the above I've mentioned other is maintainer work, so let me get that done, if that is what others agree as a way forward.

2024-04-26 18:55 UTC, kilasuit requested changes
Can we change these bits in this PR, ideally in a single commit so can in future look at v7 compatible codebases which is a larger longer term discussion point for DSCCommunity to have

2024-04-26 18:55 UTC, kilasuit commented on source/Classes/004.ManagedIdentityToken.ps1
> +        $String = ($this.linux) ? [System.Runtime.InteropServices.Marshal]::PtrToStringUni($BSTR) :
based on discussion can we change this to be able to back to v5 syntax and check based on discussion above

2024-04-26 18:55 UTC, kilasuit commented on source/AzureDevOpsDsc.psd1
> +    PowerShellVersion  = '7.0'
```suggestion
    PowerShellVersion  = '5.1'
```

2024-04-26 18:55 UTC, kilasuit commented on source/Classes/004.ManagedIdentityToken.ps1
> +    hidden [bool]$linux = $IsLinux
Perhaps this shouldn't be a check for 1 OS type unless this is definitely an only linux and not also MacOS issue to check for & not use the `$Is` automatic varibales for checking and use the v5 compatable `[Environment]::OSVersion.Platform` instead

2024-04-26 19:13 UTC, kilasuit commented
The previous comment was made based on the comment made not from having relooked at the code in this PR as was an interesting discussion point.

However on the disccusion in the DSC Channel in the slack/discord and investigation on how to check for compatibility I'm going to ask for simplicity for maintainence and use going forward for the following

- Revert to using 5.1 language features as part of this PR so can get this merged sooner rather than later & users can look to use this in their configurations.
- As part of longer term plans, bring this discussion point to the next DSC Community call, and raise a discussion for this in the PowerShell discussions org as we in DSCCommunity don't currently have discussions enabled 
- Based on the above discussion, also discuss potentially using this module as a basis for a POC of maintaining v5 and v7 together using the method I mentioned in previous comment
  - This is cleaner way forward than forking this into yet another repo that needs managed and maintained and then releasing a `AzureDevOpsDscV7` module instead (which @johlju suggested in the discussion in the dsc channel) which from historics leads to causing much more more confusion than needed when we can totally avoid that using Major Versions for seperation which I feel is the better way, if not the most correct way to do this, especially as we should keep alignment to Semver and can be easily incorporated into changelogs too which again aids discoverability

2024-04-27 01:09 UTC, ZanattaMichael commented
> The previous comment was made based on the comment made not from having relooked at the code in this PR as was an interesting discussion point.
> 
> However on the disccusion in the DSC Channel in the slack/discord and investigation on how to check for compatibility I'm going to ask for simplicity for maintainence and use going forward for the following
> 
> * Revert to using 5.1 language features as part of this PR so can get this merged sooner rather than later & users can look to use this in their configurations.
> * As part of longer term plans, bring this discussion point to the next DSC Community call, and raise a discussion for this in the PowerShell discussions org as we in DSCCommunity don't currently have discussions enabled
> * Based on the above discussion, also discuss potentially using this module as a basis for a POC of maintaining v5 and v7 together using the method I mentioned in previous comment
>   
>   * This is cleaner way forward than forking this into yet another repo that needs managed and maintained and then releasing a `AzureDevOpsDscV7` module instead (which @johlju suggested in the discussion in the dsc channel) which from historics leads to causing much more more confusion than needed when we can totally avoid that using Major Versions for seperation which I feel is the better way, if not the most correct way to do this, especially as we should keep alignment to Semver and can be easily incorporated into changelogs too which again aids discoverability

No worries. My reasoning for pwsh 7.0 to force the use of Invoke-DSC Resource rather then using the MOF since this configuration is best run within a pipeline so pwsh 7.0 would be preferred. I need to sit down and do some more work on this module, since I've been writing resources for work and I needed to refactor some of the MI code. I also plan to abstract out the PAT token, and possibly add client ID/ secret support. This will require some major rework of the module.

Thanks for getting back to me. Sorry I would of responded on discord, however I've been busy with #DadLife.

Cheers,

Michael.

2024-06-05 09:32 UTC, ZanattaMichael commented
Closing PR due to new branch with additional features.

2024-06-05 09:32 UTC, closed without merging