BREAKING CHANGE: Identity and Resource Refactor and Update - Squash Commit
dsccommunity/AzureDevOpsDsc pull request #37
Opened 2024-10-20 21:07 UTC by ZanattaMichael

#### Pull Request (PR) description

The following pull request performs a major rework of the identity and resources of the module.

1. Re-Working the caching mechanism to focus on enumeration and caching at the execution of the script.
2. Removal of PAT Tokens from Resources.
3. Removal of Api URL's from Resources.
4. Rework of authentication and separating it into it's own command: `New-AzDoAuthenticationProvider`
5. Introduction of Token retrieval protections to prevent accidental token pipeline leakage.
6. Added the following resources:
   1. xAzDevOpsProjectGroup
   2. xAzDevOpsOrganizationGroup
   3. xAzDevOpsGroupMember
   4. xAzDoGroupPermission
   5. xAzDoProjectServices
   6. xAzDoGitRepository
   7. xAzDoGitPermission
8. Renamed resource: `AzDevOpsProject` to `xAzDevOpsProject`

#### Task list

This Pull Request is currently in draft form and will be updated as more resources and features are added.

- [ ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/AzureDevOpsDsc/36)

2024-10-20 21:08 UTC, ZanattaMichael commented
Based off https://github.com/dsccommunity/AzureDevOpsDsc/pull/36

2024-11-03 22:06 UTC, ZanattaMichael commented
All sorry for the run around. I've reworked the module to be in line with the DSC Community standards and fixed a few bugs along the way. :-)

2024-11-06 16:00 UTC, kilasuit commented
FYI - I've changed what branch this points to only due how much there is here that needs to be reviewed

Just to set expectations I am setting aside time to fully review on 11th November to look at this getting merged that day.

2024-11-07 04:43 UTC, ZanattaMichael commented
Sorry I thought I responded, but I didn't. That's fine. I'll be DMing that day, but I'll keep a close eye on this.

2024-11-15 10:12 UTC, kilasuit requested changes
I've reviewed as much as i can with the motivation that I have available to me right now, without outright rejecting or abandoning this review, or the desire to keep on breathing.

Theres lots in this PR I like, lots i very much dislike too. I've likely missed things as I've been reviewing this on my energy reserves & slept for a day and half between starting and getting to this point & mostly without coffee, chocolate or basic nutriition.

I've changed this to point to a refactor branch so that we can attempt to clean all this up before it going into a prerelease or released module as I don't think it's in a fit state right now.

I also opened #38 as this needs more maintainers than just me, especially as I've not written any of the code here & I can't continue doing stuff like this for free, when I have been barely surviving for well over 2 & half years & started this with plans for it to be presented about at PSConfEU 22, however I didnt' get support to do so on part paid, part my own time, and then lost my dad to cancer & had a nightmare few years since.

I am close to walking away from all of this, however, this PR, as brutal is has been, has been somewhat enjoyable, I just dont have right now the energy to continue with this.

It perhaps should have been split into smaller PR's but for now I am done reviewing this for at least a week if not more.

2024-11-15 10:12 UTC, kilasuit commented on USAGE.md
> +  - `xDSCResourceDesigner`
PM-TODO - 
Add a section to install these using both Install-Module and Install-PSResource

2024-11-15 10:12 UTC, kilasuit commented on source/AzureDevOpsDsc.psd1
> +    )
Should this not include all the DSCResources & not just these 3?

2024-11-15 10:12 UTC, kilasuit commented on source/Classes/002.PersonalAccessToken.ps1
PM-TODO
PAT's can expire so we need there to be logic for this in the method `isExpired`

2024-11-15 10:12 UTC, kilasuit commented on source/Enum/DescriptorType.ps1
> +
remove this empty line

2024-11-15 10:12 UTC, kilasuit commented on source/Examples/Resources/AzDoGitPermission.md
> +> Either 'Name' or 'DisplayName' can be used
`@```suggestion`
> Either 'Name' or 'DisplayName' can be used, but we **Strongly Recommend** that you use `Name` in your configuration.
```

2024-11-15 10:12 UTC, kilasuit commented on source/Examples/Resources/AzDoGitPermission.md
> +                        "Manage Notes" = 'Allow'
```suggestion
                        ManageNote = 'Allow'
```

2024-11-15 10:12 UTC, kilasuit commented on source/Examples/Resources/AzDoGitPermission.md
> +                                        "Manage Notes" = 'Allow'
```suggestion
                                        ManageNote = 'Allow'
```

2024-11-15 10:12 UTC, kilasuit commented on source/Examples/Resources/AzDoGitPermission.md
> +            "Manage notes": "Allow"
```suggestion
            ManageNote: "Allow"   
```

2024-11-15 10:12 UTC, kilasuit commented on source/Examples/Resources/AzDoGitRepository/2-UpdateAzDoGitRepository.ps1
Perhaps should be a `Not currently supported`

2024-11-15 10:12 UTC, kilasuit commented on source/Examples/Resources/AzDoGroupPermission.md
> +Either 'Name' or 'DisplayName' can be used:
same as prior suggestion

2024-11-15 10:12 UTC, kilasuit commented on source/Examples/Resources/AzDoOrganizationGroup.md
> +OrgGroup
not sure this is needed

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Api/Project/Update-DevOpsProject.ps1
> +        #>
is this needed?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Api/ServicePrincipal/empty.txt
is this needed?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Cache/Get-CacheObject.ps1
> +https://github.com/Azure/AzureDevOpsDsc
```suggestion
https://github.com/dsccommunity/AzureDevOpsDsc
```

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Cache/Refresh-CacheIdentity.ps1
> +    $Identity | Add-Member -MemberType NoteProperty -Name 'ACLIdentity' -Value $ACLIdentity -Force
I dont see where `$Identity` is set is this pulled in elsewhere?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Helper/Invoke-AzDevOpsApiRestMethod.ps1
> +        This is a light, generic, wrapper proceedure around 'Invoke-RestMethod' to handle
```suggestion
        This is a light, generic, wrapper around 'Invoke-RestMethod' to handle
```

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Helper/Logging/Flush-Log.txt
Why is this a .txt file?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Helper/Logging/Initialize-Log.txt
same as prior comment

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Helper/Logging/Write-Log.txt
again why .txt ...?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Helper/PreCommandLookupAction.ps1
what is the point of this file?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/AzureDevOpsDsc.Common.psm1
> +#using module AzureDevOpsDsc
```suggestion
using module AzureDevOpsDsc
```

2024-11-15 10:12 UTC, kilasuit commented on source/Classes/040.AzDoGitRepository.ps1
> +
i'm not marking each instance like this for change, as this is boilerplate code that you should be able to fix across all the files easily enough but for date can we use ISO 8601 format of YYYY-MM-DD

2024-11-15 10:12 UTC, kilasuit commented on source/Classes/041.AzDoGitPermission.ps1
> +    https://github.com/Azure/AzureDevOpsDSC
```suggestion
.LINK
    https://github.com/dsccommunity/AzureDevOpsDSC
```

this is another common one

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Resources/Functions/Public/AzDoOrganizationGroup/Get-AzDoOrganizationGroup.ps1
> +                }
meant to be commented out....?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Resources/Functions/Public/AzDoOrganizationGroup/Get-AzDoOrganizationGroup.ps1
> +            #$getGroupResult.Reasons += [DscResourceReason]::New('AzDoOrganizationGroup:AzDoOrganizationGroup:Changed', 'The group has changed')
again is this meant to be commmented out?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Resources/Functions/Public/AzDoOrganizationGroup/Get-AzDoOrganizationGroup.ps1
> +        #$getGroupResult.Reasons += [DscResourceReason]::New('AzDoOrganizationGroup:AzDoOrganizationGroup:NotFound', 'The group is not found')
again is this meant to be commented out?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Resources/Functions/Public/AzDoOrganizationGroup/Test-AzDoOrganizationGroup.ps1
> +    if ($GetReslut.Status -eq [DSCGetSummaryState]::Unchanged )
```suggestion
    if ($GetResult.Status -eq [DSCGetSummaryState]::Unchanged )
```

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Resources/Functions/Public/AzDoProjectServices/New-AzDoProjectServices.ps1
What is the point in this function if it's not triggered at all?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Resources/Functions/Public/AzDoProjectServices/Remove-AzDoProjectServices.ps1
not understanding why we'd have a public function that does nothing

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Resources/Functions/Public/AzDoProjectServices/Test-AzDoProjectServices.ps1
another ...why?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Resources/Functions/Public/New-AzDevOpsProject.ps1
This like quite a few other similar functions seem needed & do we have them elsewhere?

2024-11-15 10:12 UTC, kilasuit commented on source/Modules/AzureDevOpsDsc.Common/Services/Functions/Public/Refresh-Cache.ps1
whats the point of this?

2024-11-15 10:12 UTC, kilasuit commented on source/WikiSource/Resources/AzDoGitPermission.md
We should use name not displayname in any configurations

2024-11-15 10:12 UTC, kilasuit commented on source/WikiSource/Resources/AzDoGroupPermission.md
> +Either 'Name' or 'DisplayName' can be used:
Update to the strongly recommended comment earlier

2024-11-15 10:12 UTC, kilasuit commented on source/WikiSource/Resources/AzDoOrganizationGroup.md
> +Start-DscConfiguration -Path ./ExampleConfig -Wait -Verbose
I may be wrong in this but this doesn't look right in these examples, can we go through them all and ensure that they are right.

2024-11-15 10:12 UTC, kilasuit commented on tests/DSC/InModuleScope.ps1
> +}
why is this needed?

2024-11-15 10:12 UTC, kilasuit commented on tests/Integration/Resources/AzDoGitPermission.tests.ps1
> +
remove or add a commment here

2024-11-15 10:12 UTC, kilasuit commented on tests/Integration/Supporting/API/Get-AzDevOpsApiVersion.ps1
> +
nitpik - remove

2024-11-15 10:12 UTC, kilasuit commented on tests/Integration/Supporting/API/Invoke-APIRestMethod.ps1
> +
nitpik remove

2024-11-15 10:12 UTC, kilasuit commented on tests/Integration/Supporting/APICalls/List-DevOpsGroups.ps1
Seems theres a missing lookup in here?

2024-11-15 10:12 UTC, kilasuit commented on tests/Integration/Supporting/APICalls/Remove-DevOpsProject.ps1
> +
just read this back, given the context

2024-11-15 10:12 UTC, kilasuit commented on tests/Integration/Supporting/Functions/SupportingFunctions.ps1
> +
Add a comment or remove

2024-11-15 10:12 UTC, kilasuit commented on tests/Integration/Supporting/Teardown.ps1
> +
I can't remember if we should/should not have an empty line at end of files

2024-11-15 13:01 UTC, ZanattaMichael commented
> I've reviewed as much as i can with the motivation that I have available to me right now, without outright rejecting or abandoning this review, or the desire to keep on breathing.
> 
> Theres lots in this PR I like, lots i very much dislike too. I've likely missed things as I've been reviewing this on my energy reserves & slept for a day and half between starting and getting to this point & mostly without coffee, chocolate or basic nutriition.
> 
> I've changed this to point to a refactor branch so that we can attempt to clean all this up before it going into a prerelease or released module as I don't think it's in a fit state right now.
> 
> I also opened #38 as this needs more maintainers than just me, especially as I've not written any of the code here & I can't continue doing stuff like this for free, when I have been barely surviving for well over 2 & half years & started this with plans for it to be presented about at PSConfEU 22, however I didnt' get support to do so on part paid, part my own time, and then lost my dad to cancer & had a nightmare few years since.
> 
> I am close to walking away from all of this, however, this PR, as brutal is has been, has been somewhat enjoyable, I just dont have right now the energy to continue with this.
> 
> It perhaps should have been split into smaller PR's but for now I am done reviewing this for at least a week if not more.

Thank you for taking the time to perform the review. Right now, I'll work with other members within the DSC community to continue this review.

In terms of maintainers, going forward I would be more then happy to help out as a reviewer. It sounds that you have a lot on your plate at the moment and I'm more than happy to help out.

2024-11-17 08:50 UTC, johlju commented
FYI. I'm gonna switch the default branch back to main otherwise the pipeline wont work. Having another branch is gonna be a pain and just add even more maintenance.

2024-11-17 22:25 UTC, dan-hughes commented
@ZanattaMichael, some updates to the repository have been made to get it working and publishing.
For next steps, are you able to identify a single DSC resource (with tests, examples and dependencies) from this PR that we can move/copy into another PR to get it merged. 
Or we could disable all of the current resources and just merge the AzureDevOpsDsc.Common module as it has the most code then work on adding the resources after that?

It's a way of getting the first contribution aligned and hopefully halve the size of what's remaining in this PR.

I'm happy to assist you on this to get it moving and merged. 

Thoughts?

2024-11-17 22:51 UTC, ZanattaMichael commented
> @ZanattaMichael, some updates to the repository have been made to get it working and publishing. For next steps, are you able to identify a single DSC resource (with tests, examples and dependencies) from this PR that we can move/copy into another PR to get it merged. Or we could disable all of the current resources and just merge the AzureDevOpsDsc.Common module as it has the most code then work on adding the resources after that?
> 
> It's a way of getting the first contribution aligned and hopefully halve the size of what's remaining in this PR.
> 
> I'm happy to assist you on this to get it moving and merged.
> 
> Thoughts?

I'm open to both approaches. Disabling the resources and subsequently reintroducing them seems simpler. Alternatively, I could strip all the features from the module altogether. The issue lies with the supporting functions that these resources depend on. Should they also be separated from the module?

2024-11-18 07:22 UTC, dan-hughes commented
Typically, if some functions are used across multiple modules then they would be moved into DscResource.Common. It's good to know what's available in DscResource.Common as it means tests do not need to be written twice.

It's not critical this stage, as the module is in its infancy and is likely to change.

If the functions are solely for this module then they would live in a Common module within this repo. But I could see a situation here where the API functions may be useful to someone else but again that could be a future change to extract it into its own module.

From a module perspective it would be good to get a single resource added/updated as then the module is in a working state. 

There will be some work to enable Pester 5 in config but once everything is in place it should all become a lot easier.

2025-01-06 06:35 UTC, ZanattaMichael commented on source/Examples/Resources/AzDoGitPermission.md
> +                        "Manage Notes" = 'Allow'
Will be updated in separate commit.

2025-01-06 06:35 UTC, ZanattaMichael commented on source/Examples/Resources/AzDoGitPermission.md
> +                                        "Manage Notes" = 'Allow'
Same as above.

2025-01-06 06:41 UTC, ZanattaMichael commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Api/ServicePrincipal/empty.txt
This is not directly needed - it's more for code directory structure. Happy to remove.

2025-01-06 06:47 UTC, ZanattaMichael commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Cache/Refresh-CacheIdentity.ps1
> +    $Identity | Add-Member -MemberType NoteProperty -Name 'ACLIdentity' -Value $ACLIdentity -Force
This function is invoked by other functions

New-AzDoOrganizationGroup
Set-AzDoOrganizationGroup
New-AzDoProjectGroup
Set-AzDoProjectGroup

Essentially, when an Identity is, this function performs a lookup for the Security Identity, attaches it to the normal identity, and caches it.

2025-01-06 06:53 UTC, ZanattaMichael commented on source/Modules/AzureDevOpsDsc.Common/Api/Functions/Private/Helper/PreCommandLookupAction.ps1
That can be deleted. It was used to monitor the current Power session and prevent the of token details to the console.

2025-01-07 01:15 UTC, ZanattaMichael commented on source/Modules/AzureDevOpsDsc.Common/Resources/Functions/Public/AzDoProjectServices/New-AzDoProjectServices.ps1
For the moment, I'm just using it as a place holder. Happy to remove.

2025-01-07 01:17 UTC, ZanattaMichael commented on source/Modules/AzureDevOpsDsc.Common/Resources/Functions/Public/New-AzDevOpsProject.ps1
No this is not the same as other functions. Creating a new project uses different API calls and has a different workflow. I did abstract the cache refresh process, however this isn't the same.

2025-01-07 01:19 UTC, ZanattaMichael commented on source/Modules/AzureDevOpsDsc.Common/Services/Functions/Public/Refresh-Cache.ps1
Not required. Deleted

2025-01-07 02:01 UTC, ZanattaMichael commented on source/WikiSource/Resources/AzDoGitPermission.md
Why not? Display Names enhance readability within the configuration. However, considering both use cases is why I implemented and documented the ability to have both.

source\Modules\AzureDevOpsDsc.Common\Api\Functions\Private\Helper\ACL\ConvertTo-ACETokenList.ps1

:49 - :53
``` PowerShell
        $AllowPermissions = $ACEPermission.Keys | Where-Object { $ACEPermission."$_" -eq 'Allow' }
        $DenyPermissions  = $ACEPermission.Keys | Where-Object { $ACEPermission."$_" -eq 'Deny'  }

        Write-Verbose "[ConvertTo-ACETokenList] Iterating through the Allow and Deny Permissions and computing actions."
        $AllowBits = $SecurityDescriptor.actions | Where-Object { ($_.displayName -in $AllowPermissions) -or ($_.name -in $AllowPermissions) }
        $DenyBits  = $SecurityDescriptor.actions | Where-Object { ($_.displayName -in $DenyPermissions) -or ($_.name -in $DenyPermissions) }

        # Compute the bitwise OR for the permissions
```

2025-01-07 02:03 UTC, ZanattaMichael commented on tests/DSC/InModuleScope.ps1
> +}
Not needed. Removed.

2025-01-07 23:15 UTC, ZanattaMichael commented on source/Classes/002.PersonalAccessToken.ps1
I have reworded the comment since it was miswritten. PAT tokens do not contain information, unlike bearer tokens, which contain additional information. The only means of token validation occurs at the beginning, it verifies access to enumerating projects.

I have updated the comment to reflect this.

2025-01-07 23:38 UTC, ZanattaMichael commented on USAGE.md
> +  - `xDSCResourceDesigner`
Done.

2025-01-08 02:38 UTC, ZanattaMichael commented
@dan-hughes @kilas I have implemented the recommended changes. To advance this project I will disconnect the resources from the project (but not from the dsccommon module) and then re-add them.

Please let me know your thoughts on the matter.

2025-01-08 07:26 UTC, dan-hughes commented
azp /run

2025-01-08 07:27 UTC, dan-hughes commented
/azp run

2025-01-08 07:36 UTC, dan-hughes commented
@ZanattaMichael can you sync main on your fork and merge or rebase this branch onto it please.

CI should then run.

2025-01-14 08:42 UTC, ZanattaMichael commented
@dan-hughes Sorry for the slow response. I've been in hospital with colitis and just gotten out. I'll try and look at this next week or the following.

2025-01-19 22:05 UTC, ZanattaMichael commented
All,

Firstly, I've finally reviewed the changes, and I can see that there has been a fundamental rewriting of the pipeline testing infrastructure with this fork. This means that the two code bases have diverged significantly and this will be tricker to merge than previously thought.

The logic:

``` PowerShell
    $script:subModuleBase = $(Get-Module $script:subModuleName).ModuleBase
    $script:dscResourceName = Split-Path $PSScriptRoot -Leaf
    $script:commandName = $(Get-Item $PSCommandPath).BaseName.Replace('.Tests','')
    $script:commandScriptPath = Join-Path "$PSScriptRoot\..\..\..\..\" -ChildPath "output\builtModule\$($script:dscModuleName)\$($script:moduleVersion)\Classes\$script:dscResourceName\$script:dscResourceName.psm1"
    $script:tag = @($($script:commandName -replace '-'))
```

has been replaced by inclusion of a BeforeAll.ps1 file within the directory which loads the require dependencies need to complete the tests:

``` PowerShell
# Test if the class is defined
if ($null -eq $Global:ClassesLoaded)
{
    # Attempt to find the root of the repository
    $RepositoryRoot = (Get-Item -Path $PSScriptRoot).Parent.Parent.Parent.Parent.FullName
    # Load the Dependencies
    . "$RepositoryRoot\azuredevopsdsc.tests.ps1" -LoadModulesOnly
}
```
Considering the nature of its abstraction into a separate file, confusion can arise. The BeforeAll.ps1 file can be removed, and the code can be substituted at the beginning of the tests.

Considering how much of the logic that was updated, is that a mandatory requirement for your pipeline? I'm trying to figure out if I need to make changes to be able to shim across both pipelines.

Thoughts?

2025-01-19 22:25 UTC, dan-hughes commented
All the DscCommunity modules that I've seen/worked on use a common pattern as the module itself is based on the Sampler project.

This is kind of why I wanted to get the build working before much more is added as a lot of the tooling is already there to help with validation, localisation, doc generation etc. 
This also helps new or current contributors get up to speed and know/expect things to work a certain way. 
There is a risk that if this module diverges away then potential issues or fixes in DscResource.*  modules may cause this project to break.

@johlju thoughts on the above?

2025-01-19 22:47 UTC, dan-hughes commented
@ZanattaMichael, are you looking at using class based resources only?

2025-01-19 23:13 UTC, ZanattaMichael commented
> @ZanattaMichael, are you looking at using class based resources only?

Correct.

2025-01-19 23:36 UTC, dan-hughes commented
That makes things a little easier.

I think the following as a plan:
- disable all tests (unit and integration)
- remove any of the pipeline changes in this fork
- rebase main onto this fork
- as it's all class resources, the .Common module is not required. It's an old convention and all additional functions can live in the Private/Public directories of the module
- let it build
- if it builds, merge this PR
- additional PR's to start re-enabling tests using the common test format used in other modules
- enable HQRM checks
- add string localization

This is an easy ish way to get this PR merged and start moving forward with smaller and easier to review PR's moving forward.

2025-01-20 11:40 UTC, johlju commented
I think @dan-hughes covered it nicely. 

I can just add that this module should not invent its own pipeline for testing. One other important aspect of writing tests is that it is okay to duplicate test code - it makes it much easier for other contributors to continue adding/changing tests. A test file should also be standalone (and use DSC community pattern for initiating tests) and should not dot source test code from other files, that makes it more complicated for other contributors to read tests - which is already hard for new contributors.

2026-08-07 08:51 UTC, ZanattaMichael commented
Hey I'm really sorry for the inaction on this PR. I kinda lost interest and willingness to finish it and it fell to the wayside - I was just trying to get all the different resources completed and tested in a timely manner. And DSC v3 came out and I felt so overwhelmed. Recently over the last few months, with sonnet and opus's help, I was able to finish the remainder of the resources and the associated integration tests that support it.

I'm not sure where to take it and if it's even possible to merge this resource.
Happy to close it or we look a naming it something different? I don't know.

2026-08-12 04:29 UTC, ZanattaMichael commented
Closing PR as it's not possible to re-combine codebases.

2026-08-12 04:29 UTC, closed without merging